# Configuration for the 'infra' cluster
BRIDGE_INTERFACE="enp8s0"

CLUSTER_NAME="infra"

# --- Control Plane Node Configuration ---
CONTROL_PLANE_COUNT=1
CONTROL_PLANE_CPU=2
CONTROL_PLANE_MEM="4G"
CONTROL_PLANE_DISK="20G"

# --- Worker Node Configuration ---
WORKER_COUNT=1
WORKER_CPU=4
WORKER_MEM="12G"
WORKER_DISK="40G"
